agentos-project/agentos

documentation/architecture_and_design.rst, documentation/index.rst, documentation/motivation.rst, documentation/quickstart.rst
A few small edits:
* `agent.step()` -> `agent.advance()`
* Capitalize Python (believe this is standard)
* Remove trailing whitespace
* "Codify" a few things that seemed reasonable to codify (e.g. `False` when referring to the Python boolean)
* A few minor rewrites for clarity
How would you feel if I reflowed the paragraphs to be 80 chars max per line?  Makes editing and diffs easier to read IMO.
=> Minor documentation edits

documentation/architecture_and_design.rst, documentation/example_agents.rst, documentation/index.rst, documentation/motivation.rst, documentation/quickstart.rst
As proposed in PR #14, I think this makes diffs easier to read (see, for example, 4ae0608).  I built the docs locally and manually compared them to the live docs to confirm this didn't affect styling.
Also, capitalized Python in index.rst again 😄
=> Reflowed doc RSTs to have 80 chars per line

documentation/build_docs.py, documentation/build_readme.py
Minor updates to build_docs.py and build_readme.py that shouldn't change functionality:
* Use `os.sep` instead of `/`
* Use `os.pardir` instead of `..`
* Use `os.path.join` instead of format strings
Theoretically, should make these scripts more likely to run on windows (though, I haven't actually tested on windows)
=> Use os.sep and os.pardir

dev-requirements.txt, scripts/format_code.py, scripts/lint_code.py, scripts/shared.py
Adds two Python scripts to automatically format and lint Python code.  These will specifically only run on Python files tracked by git (and not, for example, Python files in packages in a virtualenv you keep untracked in the git repo).
To format with black: `python scripts/format_code.py`
To lint with flake8: `python scripts/lint_code.py`
I specifically did **not**:
* Set up any particular rules for formatting and linting.  Let's figure out a reasonable configuration once this gets in (or we could just use defaults, which I think conform to the pep8 style guide)
* Run the formatter on the existing code.  Let's wait until we decide on how to configure the formatter.
Per our conversation earlier, the [black repo](https://github.com/psf/black) has 19k stars and 1k forks which makes me think …
=> Add scripts to format and lint code

.github/workflows/run-format.yml, .github/workflows/run-lint.yml, .github/workflows/run-tests.yml, scripts/format_code.py
Breaks out the format and lint github actions into their own flows so the tests will still run even if black or flake8 raises an issue.
=> Separate format and lint github actions

README.rst, documentation/includes/developing.rst, documentation/includes/intro.rst, scripts/build_docs.py, scripts/build_readme.py, scripts/shared.py
* Found the link on the github testing badge was broken so fixed that in b1ff04a
* Decided to knock out https://github.com/agentos-project/agentos/issues/48 while I was in there (although, I'll hold off on fixing "good first issues" in the future)
=> Move documentation build scripts and fix link to github tests

test_all.py
Because of the synchronization issues with the ChatBot and the threaded env, this changes the test to directly instantiate a ChatBot rather than relying on `run_agent`.
Test:
```
pytest test_all.py -rP -v -k 'test_chatbot'
```
=> Fix flaky chatbot test

README.rst, documentation/includes/developing.rst
Addresses [Issue 78: Add design doc process to documentation](https://github.com/agentos-project/agentos/issues/78).
The [PR](https://github.com/agentos-project/design_docs/pull/1) in the `design_docs` repo adds much more detail its README about the process. See [here](https://github.com/agentos-project/design_docs/blob/00e28049aa46797e55be76c202849c41aeac34ce/README.rst).
=> Update README with details about design doc repo

agentos/version.py, documentation/programming_agents.rst
Per the release process I'm tracking in #103, this updates the working version of the `master` branch to have the "-alpha" suffix.
Also fixes a small bug I noticed in the docs while reviewing them before publishing them.
=> Bump version to 0.1.0-alpha & fix typo in docs

README.rst, dev-requirements.txt, documentation/includes/developing.rst, documentation/includes/install_and_try.rst
This partially addresses #67 by just removing the offending link (since it was causing PyPI upload to fail while trying to push release 0.0.7 to PyPI). It does not guarantee that we won't accidentally use Sphinx-specific references that don't make sense in the README.
=> update docs/readme based on lessons learned cutting release 0.0.7

README.rst, documentation/design_docs/README.rst, documentation/design_docs/abstractions.rst, documentation/design_docs/registry.rst, documentation/includes/developing.rst
Per https://github.com/agentos-project/design_docs/discussions/8, this copies over the existing design_docs and updated readme. It also updates references to the design process in the main agentos documentation (i.e., in the README and the website).
After we merge this PR, next steps are:
1. move over the open discussion threads from the `design_docs` repo
2. archive `design_docs` repo
=> copy design docs and updated readme from design_docs repo

agentos/__init__.py, agentos/agents.py, agentos/cli.py, agentos/core.py, example_agents/predictive_coding/free_energy_tutorial/main.py, example_agents/rl_agents/dqn_agent.py, example_agents/rl_agents/random_nn_policy_agent.py, example_agents/rl_agents/reinforce_agent.py, registry.yaml, test_all.py
Initial (rough) port of `agentos {init, train, test}` command-line tools to the new abstractions.  Issuing this PR in case you all want to start writing code against these changes.
See [design discussion](https://github.com/agentos-project/design_docs/discussions/5) here.
```bash
mkdir andy_agent
cd andy_agent/
agentos init . -n AndyAgent
agentos learn 5
agentos run
agentos install 2048
agentos run
```
This is a very rough first stab, some limitations:
* ~~I assume you will be running these commands within the agent directory (and don't support specifying  custom `agent.ini` yet)~~ `train` and `run` now support a `-f` flag to specify the `agent.ini` to use.
* I skipped all but ~~one~~ two of the tests (😬).  They'll come back online as we port example agents and `run_agent` to the new …
=> Initial port of CLI to new abstractions

agentos/cli.py, agentos/core.py, agentos/runtime.py, agentos/templates/environment.py, registry.yaml, tests/test_core.py
A few small features that helped with debugging as I was finishing the Acme R2D2 port:
* `agentos reset` removes any data backing the agent (e.g. NNs backing a policy, training statistics) so you can re-train from scratch.  `agentos reset -b [backup UUID]` restores the agent backing data specified by the UUID.  I imagine the mechanisms for these might change as you get deeper into your work on hierarchical components and MLFlow.
* Added back in the `--max-iters` flag (renamed to `--max-transitions`) for `agentos run` and `agentos learn`.
* Updated the default environment (the corridor environment you get after `agentos init`) so that it will work with the Acme R2D2 agent.  For example:
```
mkdir corridor_agent
cd corridor_agent
agentos install acme_r2d2_policy
agentos install …
```
=> `agentos reset` and other minor functionality updates

agentos/component.py, agentos/registry.py, agentos/runtime.py, agentos/utils.py
This PR makes the following possible in the REPL (modulo some parameter issues noted below):
```python
from agentos.registry import Registry
registry = Registry()
component = registry.get_component("acme_r2d2_agent")
acme_r2d2_agent = component.get_instance()
acme_r2d2_agent.evaluate(num_episodes=10)
```
This code works against a dummy registry that associates the name `acme_r2d2_agent` with the corresponding example agent in AgentOS available on Github.  It clones the repo and does the necessary DAG setup to enable the `evaluate()` call.
To run this demo: `python agentos/registry.py`
Caveats:
* We don't handle requirements so you need to have the Acme R2D2 requirements installed in your env.
* The parameter system still needs refinement.  In a complex agent like this, it's not clear how …
=> Implementation of Component Registry v2

agentos/cli.py, agentos/component.py, agentos/repo.py, agentos/utils.py, tests/example_agents/test_acme_dqn.py, tests/example_agents/test_acme_r2d2.py, tests/example_agents/test_gh_sb3.py, tests/example_agents/test_others.py, tests/example_agents/test_rllib.py, tests/example_agents/test_sb3.py, tests/test_component.py, tests/utils.py
This PR adds functionality to take a Component DAG and pin the version of each Component to a publicly available version on GitHub.  The resulting spec can then be run on any machine where AgentOS is installed.
```bash
cd example_agents/sb3_agent/
agentos run agent
agentos pin agent
mkdir ~/demo
cp agentos.yaml ~/demo/
cd ~/demo
agentos run agent
```
Before pinning, we require that each Component in the dependency tree:
* Be in a repo (not necessarily the same repo) whose `origin` is a GitHub URL
* That the local repo branch has a corresponding branch on `origin` and both branches are at the same commit
* That there are no uncommitted changes in the repo
=> Ability to pin a version of a spec file

agentos/agent_run.py, agentos/run.py, agentos/utils.py, example_agents/acme_dqn/agent.py, example_agents/acme_dqn/network.py, example_agents/acme_dqn/requirements.txt, example_agents/acme_dqn/run.py, example_agents/acme_r2d2/agent.py, example_agents/acme_r2d2/components.yaml, example_agents/acme_r2d2/network.py, example_agents/acme_r2d2/requirements.txt
This Fixes #233. Update the dqn (and r2d2) agent to successfully load and save to tensorflow, using MLflow as the mechanism for communication between runs.
This is based onto top of #234
=> Fix broken model saving/loading via mlflow in acme agents (fix #233)

README.rst, documentation/includes/developing.rst, tests/test_specs.py, tests/test_web_registry.py, tests/utils.py, web/registry/tests/test_integration.py
Since some of our tests fetch source code from the agentos-project GitHub repo, it is helpful to be able to have that code depend on a branch that is easy to change in one place.
This will allow PR branches to easily use a `test_staging` branch and then after the PR is approved -- right before it is merged -- we can push update the `test_prod` branch to match the `test_staging` branch and change the code to use the `test_prod` branch.
I don't love the solution, but it seems much better than what we had before which is tests that depend on various static branches that we then have to hunt down an push updates to.
=> Allow easy swapping of target branch for tests that use code from github

agentos/cli.py, agentos/component.py, agentos/component_run.py, agentos/registry.py, agentos/run_command.py, tests/test_component.py, tests/test_registry.py, tests/test_run.py, web/registry/tests/test_integration.py, web/registry/tests/test_registry.py
NOTE: this is based on #263. Let's merge that first!
We've been talking about making`Component.run()` easier to use by getting rid of the burden of building an `ArgumentSet`. This does that by renaming the existing version of the function (which has lots of knobs and requires an ArgumentSet) to be `Component.run_with_arg_set()` and having the `run()` function itself be simpler and behave more like the entry point function itself, e.g.: you just pass the entry point args directly into the `run()` function and get back the return value.
The trade-off is that you don't get a pointer back to the ComponentRun that was created.
This also adds a convenience function `Registry.from_repo()`.
Demo:
```python
import agentos
repo = agentos.Repo.from_github("agentos-project", "agentos")
reg = …
```
=> Make it easier (and more intuitive?) to use `Component.run()`

agentos/component.py, agentos/registry.py, agentos/repo.py, agentos/utils.py
Based on your work in #264 , this PR backs out the hacky `Repo` manipulation stuff I was doing in #260 and creates a function that basically wraps your demo from #264 into a single function call.
Same (well, slightly updated) demos from #260:
```python
from agentos import Component
component = Component.from_github_registry("https://github.com/agentos-project/agentos/blob/master/example_agents/sb3_agent/components.yaml", "sb3_agent")
component.run('evaluate')
```
```python
from agentos import Component
from agentos import ArgumentSet
import yaml
import requests
component = Component.from_github_registry("https://github.com/agentos-project/agentos/blob/master/example_agents/acme_r2d2/components.yaml", "agent")
arg_set = ArgumentSet(yaml.safe_load(requests.get('https://github.com/agentos-pro …
```
=> Clean up `Component.from_github_registry()` implementation 

README.rst, agentos/version.py, scripts/build_readme.py, setup.py
0.1.0 Release Notes:
* Introduces a new architecture which has two main layers:
* The lower layer Python Component System (PCS) which consists of `Registry`s (`InMemoryRegistry` and `WebRegistry`) and "Spec Objects" that include `Repo`s (`InMemoryRepo` and `GitHubRepo`), `Component`, `RunCommand`, and `Run`/`ComponentRun`.
* The higher layer AgentOS: which builds RL & agent related tools on top of the lower layer PCS abstractions.
* Reworks CLI to support new abstractions.
* Adds a Django web application that serves as a RESTful WebRegistry for hosting and sharing components.
* New example agents that demonstrate the integration of PCS and AgentOS with existing RL frameworks like [Acme](https://github.com/deepmind/acme), [Stable Baselines3](https://github.com/DLR-RM/stable-baselines3), …
=> 0.1.0 release

agentos/component.py, tests/test_component.py
Fixes #276; moves Component import and instantiation in `get_object()`.  Clears the way for work on #280 .
=> Import and instantiate Components in get_object()

agentos/cli.py, agentos/component.py, agentos/virtual_env.py, tests/test_registry.py
As the title says, this PR moves venv management into the Component.  It also cleans up the VirtualEnv API a little bit (~~will create an additional issue for further improvements~~ see #297): 
The following demo now works (note, no manual venv management required).  First in bash, create a new empty Python environment to run the demo script and install agentos:
```bash
virtualenv -p /usr/bin/python3.9 test_env
source test_env/bin/activate
pip install -e .
```
Now try to manually build and run the sb3_agent in the Python REPL:
```python
from agentos import Repo, Component
aos_repo = Repo.from_github("agentos-project", "agentos")
sb3_agent = Component.from_repo(repo=aos_repo, identifier="sb3_agent==master", class_name="SB3PPOAgent", file_path="example_agents/sb3_agent/agent.py", …
```
=> Integrate VirtualEnv management into Component

agentos/cli.py, agentos/component.py, agentos/repo.py, agentos/utils.py, agentos/virtual_env.py, example_agents/rllib_agent/requirements.txt, example_agents/sb3_agent/requirements.txt, install_requirements.py, setup.py, tests/test_agents/setup_py_agent/agent.py, tests/test_agents/setup_py_agent/setup.py, tests/test_venv_management.py
This PR  allows virtual environments to be created based on the `install_requires` kwarg found in `setup.py` files.  Also included in this PR:
* More cache-clearing commands:
* `agentos clear-env-cache`
* `agentos clear-repo-cache`
* `agentos clear-cache  # clears both env and repo cache`
* You can list multiple requirements files (Python package `setup.py` files or pip-compatible `requirements.txt` files) in the `requirements_path` Component spec key separated by a semicolon and all will be installed into the virtual env.
* Update to `rllib_agent` and `sb3_agent` requirements.
* Minor improvements to the `install_requirements.py` environment setup script.
* Remove unneeded requirements from AgentOS `setup.py`.
Try the following demo in your Python REPL to get a Policy class component out …
=> VirtualEnv can be created from setup.py files

agentos/component.py, agentos/virtual_env.py, tests/test_venv_management.py
This PR makes it so that when we're building and running a Component DAG with one or more `requirements_path`'s defined, we only activate the virtual env built out of those requirements once and never deactivate.  
I think this is the most reasonable behavior given that:
* It is impossible to isolate dependencies for different components in CPython (see write up [here](https://docs.google.com/document/d/1i1AoTF63IUh9hgYBgxdBRsbBgwD8YvKJ9HbwRwR_L68/edit#heading=h.5skdbrwtmflo))
* Some libraries make changes to the environment when they are imported that they expect to persist (e.g. manipulation of the `sys.path`)
* We support the `get_object()` flow and that object expects to run in its environment.
I added a local check to `Component.add_dependency()` to make sure you weren't doing …
=> Only activate a Component's venv once

example_agents/rllib_agent/requirements.txt, example_agents/sb3_agent/requirements.txt, install_requirements.py
Up until now,  on my Macbook Pro M1 I've been ignoring the rllib tests which have failed with a segfault.
However I recently:
1. switched to the arm64 version of brew (I previously had installed the x86 vesion which I guess was using rosetta for much of what it was installing?)
2. used that new brew to re-install conda
3. made a new env
4. installed scipy via conda (since installing scipy via pip tries compiling numpy on apple silicon which fails)
5. tried pip installing sb3 requirements, and this fails because apparently torch 1.9.1 is not available on MacOS w/ apple silicon, but 1.9.0 is.
so this changes the version of torch in the example_agent requirements.txt file to 1.9.0, which fixes the error on my Macbook Pro (MBP) M1.
Also, this PR updates the string we look for in sys.platform …
=> Fixes broken install of dev-requirements on apple silicon (Apple M1 Macbook Pro)

pcs/registry.py, pcs/repo.py, tests/test_registry.py
One of our tests exercises `Registry.from_repo_inferred` but is failing because we forgot to update the module file we expected it to be loaded from after the file referenced (component.pay) moved from `AgentOS` to `PCs `.
This didn't cause a test failure during PR review because of a bug in [the way we are using] porcelain that results in some files in the master branch of any GitHub repo not getting removed when the repo's version is non-master.
This also removes a call to `porcelain.fetch()` that was added in https://github.com/agentos-project/agentos/commit/8d377914f8e153df2bf4429608aaac7ffb67ee32 that slows down the Registry.from_repo_inferred test `but didn't seem to fix the problem documented in #310
=> fix a broken test that wasn't caught in #328

README.rst, documentation/includes/developing.rst, pcs/version.py
This is the release PR for version 0.1.1 of AgentOS and the Python Component System (PCS).
* Allow a Component to be a managed module, as an alternative to the existing support for a Component being a managed class or class instance ([#295](https://github.com/agentos-project/agentos/pull/295))
* Integrate VirtualEnv management into Component ([#296](https://github.com/agentos-project/agentos/pull/296))
* Separation of AgentOS and PCS into different top-level modules.  Most non-RL-specific functionality of the project can now be accessed by importing module `pcs` ([#328](https://github.com/agentos-project/agentos/pull/328))
* Delete Component.Identifier and replace all uses of it with ComponentIdentifier ([#290](https://github.com/agentos-project/agentos/pull/290))
* Simplify …
=> 0.1.1 release

pcs/version.py
This is the release PR for version 0.2.0 of AgentOS and the Python Component System (PCS).
* Allow a Component to be a managed module, as an alternative to the existing support for a Component being a managed class or class instance ([#295](https://github.com/agentos-project/agentos/pull/295))
* Integrate VirtualEnv management into Component ([#296](https://github.com/agentos-project/agentos/pull/296))
* Separation of AgentOS and PCS into different top-level modules.  Most non-RL-specific functionality of the project can now be accessed by importing module `pcs` ([#328](https://github.com/agentos-project/agentos/pull/328))
* Delete Component.Identifier and replace all uses of it with ComponentIdentifier ([#290](https://github.com/agentos-project/agentos/pull/290))
* Simplify …
=> 0.2.0 release

pcs/repo.py, pcs/utils.py, tests/test_repo.py
Fixes #348 
I did a little digging in dulwich and found that someone had seemingly fixed our checkout issue in a partially-unmerged pull request [here](https://github.com/jelmer/dulwich/pull/898).  I wrote a regression test, ported their `checkout()` code into our utils, and now things seem to be working correctly.
Regression demo:
```bash
git checkout baae07da1b5cd2da6518d394313670f146b448dc
agentos clear-cache -y
pytest tests/test_repo.py::test_repo_checkout_bug
git checkout nj_dulwich_fix_2
agentos clear-cache -y
pytest tests/test_repo.py::test_repo_checkout_bug
```
=> Fix dulwich checkout

agentos/cli.py, agentos/core.py, dev-requirements.txt, documentation/design_docs/registry.rst, documentation/programming_agents.rst, example_agents/acme_dqn/network.py, example_agents/sb3_agent/sb3_run.py, pcs/component_run.py, pcs/registry.py, pcs/repo.py, pcs/run.py, pcs/virtual_env.py, scripts/build_docs.py, scripts/build_readme.py, scripts/format_code.py, web/registry/tests/test_registry.py, web/registry/views.py
I was taking a look at the [gym repo](https://github.com/openai/gym/blob/master/.pre-commit-config.yaml) and noticed that they were using [codespell](https://github.com/codespell-project/codespell) and [pyupgrade](https://github.com/asottile/pyupgrade) in addition to the other static formatting and linting packages we already use (black, isort, and flake8).  
I love me a good formatter and/or linter, so I added the ones we were missing.
=> Add codespell and pyupgrade to our code formatting

pcs/git_manager.py, pcs/repo.py, pcs/utils.py, tests/test_repo.py
This PR doesn't change any public functionality, just how we use dulwich to manage the repo cache.  Main changes:
*  I collected all the dulwich functionality scattered around `repo.py` and `utils.py` and dropped it into a `GitManager` class that `repo.py` now uses for lower-level git functions.
* We map all "versions" (sha1 hashes, branch names, or tag names) to a sha1 hash and then create a repo specifically for that hash in the cache.
* We also checkout a "default repo" for each GitHub project which isn't used at PCS runtime other than to map tag and branch names to sha1 hashes and to check what commits exist on the remote.
* We occasionally run a fetch on the default repo (once per process touching it and/or every 30 minutes in the case of long running processes) to get updated refs. …
=> Always use hashes for cached repos; dulwich refactor

pcs/git_manager.py
Small optimization to the `GitManager`.  Because we've already cloned the repo in the `_default` cache, we don't actually have to pull from GitHub to clone the repo at a particular sha1.  Instead, we just clone the local default repo and checkout at the hash.
=> Git manager optimization

documentation/demos/demo_papag_in_py_repl.py
Uses the new name of the SB3 agent (`sb3_agent` instead of `agent`) in `documentation/demos/demo_papag_in_py_repl.py`.
I'm just going to merge because this fix is small!
=> Fix small bug in demo papag script

example_agents/gh_sb3_agent/components.yaml, pcs/git_manager.py, tests/example_agents/test_gh_sb3.py, tests/test_specs.py
Another small tweak to `github_manager.py` to handle remotes better.  
I was working on a local branch that was tracking your branch `spec_structure_revamp` on your agentos fork at `andyk/agentos` and pushing my changes to branch `spec_structure_revamp` on my agentos fork at `nickjalbert/agentos`.  Our git-handling code was getting confused because it wasn't seeing my commits on the tracking branch in your fork (even though they were publicly available on my fork).  
This PR updates our code to check all remotes to see if the current commit is available on any of the ones that point to GitHub.  I think this make the `remote` argument unnecessary because we'll check all remotes regardless of the name.
=> Handle multiple remote scenario better

example_agents/acme_dqn/requirements.txt, example_agents/acme_r2d2/requirements.txt
Small fix in the acme requirements to manually resolve a pip dependency conflict that significantly slows down the environment setup.
Brings dependency install time down from [~11ish minutes](https://github.com/agentos-project/agentos/runs/6830742508) to [~4ish minutes](https://github.com/agentos-project/agentos/runs/6831176117) on Ubuntu.
=> Fix pip dependency resolver issue

agentos/agent_run.py, web/leaderboard/templates/leaderboard/index.html, web/leaderboard/views.py, web/registry/models.py
Note: based on PR #400 
This ports the leaderboard landing page (i.e. [http://localhost:8000/](http://localhost:8000/)) to the new Component model.  Here's the result after some local testing:
A demo script:
```bash
cd example_agents/sb3_agent
rm -rf mlruns/
agentos run sb3_agent --function-name learn
agentos run sb3_agent --function-name evaluate
USE_LOCAL_SERVER=True agentos publish <agent run ID printed out after previous previous command>
```
Next on my list is to port:
* The run details page (currently the links just go to the API endpoint) 
* The tests
=> Port leaderboard home page to new Component model

web/leaderboard/templates/leaderboard/index.html, web/leaderboard/templates/leaderboard/run_detail.html, web/leaderboard/views.py, web/registry/models.py
This PR ports forward the run_detail view to the new models.  To demo, click the run ID here:
And you should be taken to a page like this:
Here's the demo script to populate the DB again:
```bash
cd example_agents/sb3_agent
rm -rf mlruns/
agentos run sb3_agent --function-name learn
agentos run sb3_agent --function-name evaluate
USE_LOCAL_SERVER=True agentos publish <agent run ID printed out after previous previous command>
```
Next on my list is to port:
* ~~The run details page (currently the links just go to the API endpoint)~~
* The run overview page (http://localhost:8000/runs)
* The tests
=> Port forward run_detail view

example_agents/gh_sb3_agent/components.yaml, tests/utils.py, web/leaderboard/templates/leaderboard/index.html, web/leaderboard/templates/leaderboard/runs.html, web/leaderboard/urls.py, web/leaderboard/views.py, web/registry/models.py
This ports the run overview page ([http://localhost:8000/runs](http://localhost:8000/runs)) to the new models.
Here's the demo script to populate the DB again:
```bash
cd example_agents/sb3_agent
rm -rf mlruns/
agentos run sb3_agent --function-name learn
agentos run sb3_agent --function-name evaluate
USE_LOCAL_SERVER=True agentos publish <agent run ID printed out after previous previous command>
```
Next on my list is to port, next up are the tests:
* ~~The run details page (currently the links just go to the API endpoint)~~
* ~~The run overview page (http://localhost:8000/runs)~~
* The web tests
=> Port runs page to new models

pcs/git_manager.py
This PR silences the dulwich spam (e.g. "Counting objects 1/3000") in the github test logs.  We still have a lot of noise, but now it's from PCS/AOS proper and we clean that up as desired.
[Example logs with this change](https://github.com/agentos-project/agentos/runs/6965505960?check_suite_focus=true)
=> Silence dulwich spam in github tests

agentos/agent_run.py, pcs/registry.py, web/registry/admin.py, web/registry/models.py, web/registry/views.py
This PR gets artifact upload working again.  
I think this is the shortest path to getting us back to sharing models; this is basically just porting forward the upload system to the new spec revamp.  
Longer term, we should think more about artifacts being explicitly represented in the DAG (maybe something like a file-in and file-out component?) rather than doing this via a "side-channel" as we do here.
Demo:
```bash
cd example_agents/sb3_agent
rm -rf mlruns/
agentos run sb3_agent --function-name learn
agentos run sb3_agent --function-name evaluate
USE_LOCAL_SERVER=True agentos publish <id of agent run printed after previous command>
```
If you follow the demo, all the AgentRuns should have tarballs associated with them that contain the model that was trained/evaluated.  For example:
=> Upload artifacts when publishing AgentRuns
